name: CI Pipeline  # Nome do workflow

on: # Eventos que vão disparar o pipeline
  push:   # O pipeline será executado quando houver um push
    branches:
      - main  # Especifica a branch que vai disparar o workflow
  pull_request:  # O pipeline será executado em pull requests
    branches:
      - main  # Especifica a branch para pull requests

jobs:
  build:
    runs-on: ubuntu-latest  # Ambiente de execução

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Faz checkout do repositório

      - name: Set up JDK 11
        uses: actions/setup-java@v1  # Configura o Java 11
        with:
          java-version: '11'

      - name: Build with Gradle
        run: ./backend/gradlew build  # Para projetos Gradle

      - name: Run tests
        run: ./gradlew test  # Para rodar testes
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

